apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-logger
  template:
    metadata:
      labels:
        app: k8s-logger
    spec:
      containers:
      - name: k8s-logger
        image: bettercallsaud/k8s_logger:1.0.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"